<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.4</version>
		<relativePath/>
	</parent>

	<groupId>paybank</groupId>
	<artifactId>hexagonal</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>paybank</name>
	<description>Projet de paiement bancaire en ligne avec architecture hexagonale</description>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>com.stripe</groupId>
			<artifactId>stripe-java</artifactId>
			<version>32.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		
		<!-- Apache PDFBox pour la génération et l'impression des PDF -->
		<dependency>
			<groupId>org.apache.pdfbox</groupId>
			<artifactId>pdfbox</artifactId>
			<version>3.0.1</version>
		</dependency>

		<!-- Spring Boot Starter Mail pour l'envoi des e-mails avec pièces jointes -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>
		
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>0.12.5</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>0.12.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>0.12.5</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.5.0</version>
		</dependency>
		<dependency>
			<groupId>io.gatling</groupId>
			<artifactId>gatling-test-framework</artifactId>
			<version>3.10.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.gatling.highcharts</groupId>
			<artifactId>gatling-charts-highcharts</artifactId>
			<version>3.10.3</version>
			<scope>test</scope>
		</dependency>
		<dependency>
    		<groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-testcontainers</artifactId>
    		<scope>test</scope>
		</dependency>
		<dependency>
    		<groupId>org.testcontainers</groupId>
    		<artifactId>junit-jupiter</artifactId>
    		<scope>test</scope>
		</dependency>
		<dependency>
    		<groupId>org.testcontainers</groupId>
    		<artifactId>postgresql</artifactId>
    		<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- Configuration Spring Boot -->
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>com.paybank.hexagonal.main.PaiementApplication</mainClass>
				</configuration>
			</plugin>

			<!-- Surcharge du compilateur -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>17</source>
					<target>17</target>
					<compilerArgs>
						<arg>-Xlint:none</arg>
					</compilerArgs>
				</configuration>
			</plugin>

			<!-- SonarQube Scanner -->
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>3.10.0.2594</version>
			</plugin>

			<!-- PITest Mutation Testing -->
			<plugin>
				<groupId>org.pitest</groupId>
				<artifactId>pitest-maven</artifactId>
				<version>1.15.8</version>
				<dependencies>
					<dependency>
						<groupId>org.pitest</groupId>
						<artifactId>pitest-junit5-plugin</artifactId>
						<version>1.2.1</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<phase>verify</phase>
						<goals><goal>mutationCoverage</goal></goals>
					</execution>
				</executions>
				<configuration>
					<targetClasses>
						<param>com.paybank.hexagonal.*</param>
					</targetClasses>
					<targetTests>
						<param>com.paybank.hexagonal.test.*Test</param>
					</targetTests>
					<excludedTestClasses>
						<param>com.paybank.hexagonal.test.PaiementIntegrationTest</param>
						<param>com.paybank.hexagonal.test.SecuriteAspectTest</param>
						<param>com.paybank.hexagonal.test.DroitsAopIntegrationTest</param>
						<param>com.paybank.hexagonal.test.FinancialReportControllerTest</param>
						<param>com.paybank.hexagonal.test.JournalisationBDDAspectTest</param>
					</excludedTestClasses>
				</configuration>
			</plugin>

			<!-- Gatling Plugin -->
			<plugin>
				<groupId>io.gatling</groupId>
				<artifactId>gatling-maven-plugin</artifactId>
				<version>4.6.0</version>
			</plugin>	

			<!-- OWASP Dependency-Check -->
			<plugin>
				<groupId>org.owasp</groupId>
				<artifactId>dependency-check-maven</artifactId>
				<version>9.0.9</version>
				<configuration>
					<nvdApiKey>C0C5AC4C-C62B-4873-BCF0-101AD0731400</nvdApiKey>
					<nvdApiDelay>5000</nvdApiDelay>
				</configuration>
			</plugin>
			<plugin>
	            <groupId>org.jacoco</groupId>
	            <artifactId>jacoco-maven-plugin</artifactId>
	            <version>0.8.11</version>
	            <executions>
	                <execution>
	                    <goals>
	                        <goal>prepare-agent</goal>
	                    </goals>
	                </execution>
	                <execution>
	                    <id>report</id>
	                    <phase>test</phase>
	                    <goals>
	                        <goal>report</goal>
	                    </goals>
	                </execution>
	                <execution>
	                    <id>check</id>
	                    <phase>verify</phase>
	                    <goals>
	                        <goal>check</goal>
	                    </goals>
	                    <configuration>
	                        <rules>
	                            <rule>
	                                <element>BUNDLE</element>
	                                <limits>
	                                    <limit>
	                                        <counter>INSTRUCTION</counter>
	                                        <value>COVEREDRATIO</value>
	                                        <minimum>0.90</minimum>
	                                    </limit>
	                                    <limit>
	                                        <counter>BRANCH</counter>
	                                        <value>COVEREDRATIO</value>
	                                        <minimum>0.90</minimum>
	                                    </limit>
	                                </limits>
	                            </rule>
	                        </rules>
	                    </configuration>
                	</execution>
            	</executions>
        	</plugin>
		</plugins>

		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
			</resource>
		</resources>
	</build>
</project>