spring.application.name=demo

# Connexion au conteneur PostgreSQL de Supabase
spring.datasource.url=jdbc:postgresql://supabase_db_java-backend-api:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Optionnel : pour voir les requêtes SQL dans la console pendant le développement
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# Optionnel : affiche les requêtes SQL dans les logs Docker pour deboguer
spring.jpa.show-sql=true

spring.config.import=optional:file:.env[.properties]

stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

stripe.api.key=${STRIPE_API_KEY:sk_test_valeur_par_defaut}

stripe.api.url=${STRIPE_API_URL:http://api.mokbank.internal:8080/api/v1/payments}

#rajoute en bdd les tables necessaires automatiquement
spring.jpa.hibernate.ddl-auto=update

#diagnostique securité
logging.level.org.springframework.security=DEBUG

# --- Sécurité & JWT ---
security.jwt.secret=${JWT_SECRET:cqo5B75Y+m4UgpVzeRcLvviCOGNVPLwCcLWWGt8weag=}

#pour pouvoir imprimer automatiquement
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ghislainrochette44@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Mots de passe personnalisés externalisés
user.admin.password=${ADMIN_PASSWORD}
user.manager1.password=${MANAGER1_PASSWORD}
user.manager2.password=${MANAGER2_PASSWORD}
user.employe1.password=${EMPLOYE1_PASSWORD}
user.employe2.password=${EMPLOYE2_PASSWORD}
user.employe3.password=${EMPLOYE3_PASSWORD}

# Mots de passe standard requis lors d'un changement de rôle
app.passwords.admin=${STANDARD_ADMIN_PASS}
app.passwords.manager=${STANDARD_MANAGER_PASS}
app.passwords.employe=${STANDARD_EMPLOYEE_PASS}

#spring.profiles.active=test